<style type="text/css">
<!--
#divFiles{
	padding:10px;
	width:95%;
	margin-left: auto; 
	margin-right: auto;
	margin-top:15px;
	border: solid 1px rgb(0, 133, 195);
	border-radius:5px;
	min-height:500px;	
}
.selected{
	background-color: rgb(0, 133, 195);
    border-radius: 5px;
    color: white;
    font-size: 14px;
    margin-left: 5px;
    opacity: 0.8;
    padding: 5px;
    text-decoration: none;
}
/* ====================== Overlay Options ========================= */
.divFilesGeneral{
	color: #0c5093;    
    font-size: 12px;
    font-weight: bold;
    margin: 0px 0px 3px 0px;
    max-height: 13px;
    overflow: hidden;
    padding: 3px;
}
/* ======== Add form style ============ */
.input{    
    border: solid 1px #bdc3c7;;
    border-radius: 5px;    
    height: 30px;
    margin-bottom: 15px;
    text-align: left;
    width: 40%;
}
#uploadMsg{
	color: red;
	display: none;
}
#frmUploadFile{
	width: 70%;
	display: inline;
	margin-left: 10px;
}
#divUploadFileWrapper{
	padding: 10px;
}
.button {    
    background: none repeat scroll 0 0 #3498db;
	border: solid 1px #3498db;        
    color: #ecf0f1;    
    height: 30px;    
    width: 10%;	
	border-radius: 5px;
	font-weight: bold;
}
.buttonDisabled{
	background: none repeat scroll 0 0 #dedede;
	border: solid 1px #dfdfdf;        
    color: #ffffff;    
    height: 30px;
	border-radius: 5px;
	font-weight: bold;		
}
/* ======== Table options ============= */
#tblApplicationUsersToImport{
	width:98%;
	border: solid 1px rgb(245, 245, 245);
	font-size: 14px;
	text-align:center;
}
#tblApplicationUsersToImport th{	
    background-color: rgb(0, 133, 195);	 
	padding:5px; 
	color:#ffffff; 
	filter:alpha(opacity=80);	
	opacity:0.80;	
}
#tblApplicationUsersToImport tr:hover{
	background-color: rgb(245, 245, 245);	
}
-->
</style>
<script type="text/javascript">
<!--
var baseUrl = '<?php echo $this->baseUrl();?>';
var listAsync = baseUrl + '/users/user/list-async';
var addUsersToApplicationAsync = baseUrl + '/users/user/add-users-async';
//JAVASCRIPT FUNCTIONS
function addImportedUsersToApplication(){
	// Process to add users, get the button disabled
	$("#btnAddImportedUsersToApplication").prop("disabled",true).addClass('buttonDisabled').removeClass('button');
	$("#divUsersImported").html( $("#divUploadFileLoading").html() );
	// Process the form via JSON			
	$.post(addUsersToApplicationAsync, function(data){
		$("#divUsersImported").html( data.message );
		$("#btnAddImportedUsersToApplication").prop("disabled",true).addClass('button').removeClass('buttonDisabled');
     });
	return true;
}
//JQUERY functions ------------------->
$(document).ready(function(){
    // Handles upload file button
    $("#btnUploadFile").click( function(){
        var fileName = $("#usersFile");
        // Perform validation
        if( fileName.val() == '' ){
			$("#uploadMsg").html('Please select a file').show();			
			return false;
		} else {
			$("#uploadMsg").html('').hide();			
			$("#divUsersImported").html( $("#divUploadFileLoading").html() );			
			setTimeout(function(){ 
				$("#divUsersImported").load(listAsync).show();
				fileName.val('');				 
			},1000); // Load Users
			return true;			
		}
    });
    // List users pending to add to current application
    $("#divUsersImported").load(listAsync).show();
});
//-->
</script>
<div id='divFiles'>
<div id='divUploadFileWrapper'>
<span>Use one of our templates&nbsp; 
<a target='_blank' href='<?php echo $this->baseUrl.'/users/templates/onelogin-users-to-import-template.csv';?>'>CSV</a>&nbsp;or
<a target='_blank' href='<?php echo $this->baseUrl.'/users/templates/onelogin-users-to-import-template.xml';?>'>XML</a>
</span>
<form id='frmUploadFile' enctype="multipart/form-data" method="post" action='<?php echo $this->baseUrl.'/users/user/upload/'?>' target='ajaxFrame'>    	
	<input type='file' name='usersFile' id='usersFile' class='input'>
	<input id='btnUploadFile' type='submit' value='Upload' class='button'>	
	<div id='uploadMsg'></div>
</form>
<div id='divUploadFileLoading' style="display:none; width:50%; margin:0 0 0 30%;"><img style="border: none; height:30px; width:30px;" src='<?php echo $this->baseUrl(); ?>/img/loading.gif'><span class='divFilesGeneral' style="font-size:16px;">Loading, please wait...</span></div>
</div><!-- End divUploadFileWrapper -->
<div id='divUsersImported'></div><!-- End divUsersImported -->
</div><!-- End  divFiles -->