<?php if (!Zend_Auth::getInstance()->hasIdentity() ){?>
<style type="text/css">
<!--
.input{    
    border: solid 1px #bdc3c7;;
    border-radius: 5px;        
    height: 30px;
    margin-bottom: 15px;
    text-align: center;
    width: 100%;
}
.button {    
    background: none repeat scroll 0 0 #3498db;
	border: solid 1px #3498db;        
    color: #ecf0f1;    
    height: 30px;    
    width: 100%;	
	border-radius: 5px;
	font-weight: bold;
}
.center{
	width: 350px;
	margin-left: auto;
    margin-right: auto;
	border: solid 1px #2980b9;
	padding: 30px;	
}
.error{
	color: red;
	padding: 3px;
	margin-top: 5px;		
}
.logoOl{
	border-radius: 5px 5px 0 0;
	background-color: rgb(0, 56, 107);   
	filter:alpha(opacity=80);	
	opacity:0.80;    
    border: 1px solid rgb(0, 56, 107);    	
    padding: 25px 0;
    text-align: center;
    width: 410px;
	color: #ffffff;
	font-size: 20px;
}
.logoOl img {
    max-height: 60px;
    max-width: 210px;
}
-->
</style>
<div>
<br/><br/><br/>
<div class='logoOl center'>
<span><?php echo COMPANY_NAME.'&nbsp;'.Zend_Registry::get("appname")?></span>
</div>
<div class='center' style='border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;'>
<form id='frmLogin' action="<?php echo $this->baseUrl ?>/portal/index/login" method="post">
	<div><input type="text" placeholder='User Name' id="username" name="username" required autocomplete='off' value="" class='input' /></div>
	<div><input type="password" placeholder='Password' name="password" value="" required autocomplete='off' class='input' /></div>
	<div><input type="submit" name="login" value="Login" class='button'/></div>			
	<div class='error'>
		<?php echo $this->message; ?><br />
	</div>
</form>
</div>
<?php if( isset($this->versionWarning) ){?>
<div class='warning' style='width:50%; margin-left:auto; margin-right:auto; text-align: center; margin-top: 30px;' ><?php echo $this->versionWarning;?></div>
<?php }?>
</div>
<?php }?>